name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  TIBERIUS_TEST_CONNECTION_STRING: Server=tcp:localhost,1433;User=SA;Password=12345Abcde;Encrypt=true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Start server
      run: docker run --rm -e 'ACCEPT_EULA=Y' -e 'MSSQL_SA_PASSWORD=12345Abcde' --name 'mssqlserver' -d -p 1433:1433 mcr.microsoft.com/mssql/server
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
